# Config file for automatic testing at travis-ci.org

language: python

sudo: false

python:
  - "2.7"
  - "2.6"
  - "pypy"

matrix:
  allow_failures:
  - python: '2.6'
  - python: '3.4'
  - python: pypy

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
- pip install -r requirements.txt
- python setup.py install
- pip install coveralls

# command to run tests, e.g. python setup.py test
script:
- nosetests

after_success: coveralls

os:
- linux
# - osx

deploy:
  provider: pypi
  user: beni

  on:
    tags: true
    repo: abenassi/pyredatam
